[workspace]
members = ["core/engine", "cli", "core/error", "core/ast", "tools/git"]
resolver = "1"

[workspace.dependencies]

# Core dependencies
roan-engine = { path = "core/engine" }
roan-error = { path = "core/error" }
roan-ast = { path = "core/ast" }

# Other dependencies
anyhow = "1.0.89"
colored = "2.1.0"
log = "0.4.22"
thiserror = "1.0.64"
bon = "2.3.0"
dirs = "5.0.1"
