[package]
name = "roan-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
backtrace = "0.3.74"
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
log = "0.4.22"
thiserror = "1.0.64"
vit_logger = "0.1.6"
roan-engine = { workspace = true }
dirs = { workspace = true }
tar = "0.4.42"

[build-dependencies]
project-root = "0.2.2"
tar = "0.4.42"