[package]
name = "roan-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
roan-error = { workspace = true }
roan-ast = { workspace = true }
bon = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }