[package]
name = "roan-error"
version = "0.1.1"
edition = "2021"
description = "Error handling for the Roan project"
license = "MIT"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
colored = { workspace = true }
