[package]
name = "roan-error"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
colored = { workspace = true }
