[package]
name = "roan-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
roan-error = { workspace = true }
log = { workspace = true }
colored = { workspace = true }
tracing = { workspace = true }
indexmap = { workspace = true }