name: "Pull Request Labeler"
on:
  issue_comment:
    types: [ created ]

jobs:
  labeler:
    if: ${{ github.event.comment.body == '/label' && github.event.issue.pull_request }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
