name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v1.1.0, etc.

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

  build:
    name: Build for multiple platforms
    needs: changelog
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install target with rustup
        run: rustup target add ${{ matrix.target }}

      - name: Build project for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive binaries
        run: |
          zip -j binary_${{ matrix.target }}.zip target/${{ matrix.target }}/release/my-binary

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary_${{ matrix.target }}
          path: binary_${{ matrix.target }}.zip

  upload:
    name: Upload the release
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download all built artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: binary_${{ matrix.target }}

      - name: Create GitHub release and upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ needs.changelog.outputs.release_body }}
          file: binary_${{ matrix.target }}.zip
